server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.tApps.*

    topic:
      name: order_topic

  datasource:
    url: jdbc:mysql://localhost:3306/stock_manager?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true